import Head from "next/head";

import { type AppType } from "next/app";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "../lib/utils";
import { Header } from "~/components/layout/header";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Where is the Google Car?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-background flex min-h-screen flex-col gap-4">
        <Header />
        <div className="container flex flex-col">
          <Component
            className={cn(
              "bg-background min-h-screen font-sans antialiased",
              fontSans.variable,
            )}
            {...pageProps}
          />
        </div>
      </div>
    </>
  );
};

export default api.withTRPC(MyApp);
